### ISSUE TITLE
seltzer.farsetlabs.org.uk CNAME is dead

### ISSUE THREAD

**Issue by chris18890** [FarsetLabs/somebody-should#10]
**Describe the bug**
seltzer.farsetlabs.org.uk website is dead (CNAMEd to seltzer.krismurray.co.uk)

**Expected behavior**
The FSL MMS site should load

**Screenshots/Evidence**
<generic Firefox page not found>

**Additional context**
Either repoint the seltzer.farsetlabs.org.uk CNAME from seltzer.krismurray.co.uk to seltzer-farset.krismurray.co.uk or delete the record completely to take it offline (& update https://www.farsetlabs.org.uk/about/net_conf.html) as appropriate

**Comment by andrewbolster** [comment]
Pending review from @Stealthii

**Comment by chris18890** [comment]
@bolster do you still want to keep the @farsetlabs/seltzer repo?

**Comment by chris18890** [comment]
@andrewbolster ping re deleting/keeping the repo
