### ISSUE TITLE
Can't find a sign for any wifi codes

### ISSUE THREAD

**Issue by goatchurchprime** [FarsetLabs/somebody-should#12]
There are lots of unfriendly signs about insurance, codes of conduct, washing up dirty dishes, etc.  

But I still haven't found anything that tells visitors the wifi code -- which is normally the first thing anyone setting up here is going to want to know, and you can save them the embarrassment having to ask.

**Comment by awflwafl** [comment]
I’ll get a more sign up when I am next in the space (Monday). In the meantime, you’ll be able to find the Wi-Fi password in the event space, above the door to the co-working space.

**Comment by andrewbolster** [comment]
@goatchurchprime you've fallen into a bit of a crack in the onboarding because since you're taking over Adians Sensible Code membership you didn't get the standard welcome email which includes member-specific details such as the members wifi code

**Comment by goatchurchprime** [comment]
@andrewbolster How are new members supposed to read the email if they're not on the wifi?

**Comment by andrewbolster** [comment]
@goatchurchprime members aren't supposed to be able to get in the *building* without the information in the email 😁
