### ISSUE TITLE
Review somebody-should at the next Townhall

### ISSUE THREAD

**Issue by Dylan1312** [FarsetLabs/somebody-should#2]
Raise a discussion point at the November Town Hall to decide whether or not we should continue using this.

**Comment by awflwafl** [comment]
Should we prolong this to a few months?

**Comment by andrewbolster** [comment]
https://docs.google.com/document/d/1gj3sAjSZljZlWiQoqT3fbz1VAzJXqkmReIozBHFOULY/edit?usp=sharing Was technically raised in the past 2 town halls so I think this can be 'resolved'. 

Totally up for reevaluating in a few months.
