### ISSUE TITLE
New Structure(ish thing) for Farset Dojo

### ISSUE THREAD

**Issue by gingerzoealex** [FarsetLabs/somebody-should#20]
There's no "enforced" structure for the youths attending dojo, so they can pick their own projects. Sometimes it's easy for them to get distracted and lose sight of why they're there, which is to learn.

There has to be a way to ensure the kids are accountable for what they want to learn while making sure they're having fun. We can't force them to sit and learn, but we can encourage them and help them, and get them to focus on what they want to do over x amount of time. 

Without changing the current dojo style too much, I believe it's possible to add more structure. Something like a project board will let the young ones see their progress and interact with the board in a fun way.

There are a few ways of doing this but the easiest and most visual is probably a giant board - which should be easy to get. With each thing they learn, they can stick a post-it on the board. Or if they have any ideas for what the project could have in the future, they can note that. 
_A rapidly drafted visual_: 
![ninja projects](https://user-images.githubusercontent.com/32307798/52537045-de835900-2d59-11e9-8bfe-810593333216.png)

**Comment by andrewbolster** [comment]
This was done, and worked really well, and will be continued after the restart
