### ISSUE TITLE
Bring Discourse Back From The Dead

### ISSUE THREAD

**Issue by andrewbolster** [FarsetLabs/somebody-should#24]
We used to have a relatively active Discourse, but it's been dead for a while. 

There is a "deprecated" azure based one that was set up at some point but I can't see any credentials for it anywhere. 

Should be easy enough to start one from scratch.

**Comment by andrewbolster** [comment]
* Killed old discourse VM's/Disks/IP's from Azure, 
* Spun up new blank Ubuntu LTS image on D1v2
* Used SSHkey from my account on Kitchensync as base key ID
* Followed [these](https://github.com/discourse/discourse/blob/master/docs/INSTALL-cloud.md) instructions, using the sendgrid as the SMTP relay
* Configured Google OAuth under bolster@farsetlabs.org.uk -> Discourse project
* Added [solved](https://github.com/discourse/discourse-solved), [assign](https://github.com/discourse/discourse-assign) [voting](https://github.com/discourse/discourse-voting), and [user-notes](https://github.com/discourse/discourse-user-notes) plugins
* Set @farsetlabs.org.uk emails to automatically be trusted
* Setup Unattended Upgrades and fail2ban

**Comment by chris18890** [comment]
I did see the CT notifications for the SSL certs, LGTM! :)

**Comment by andrewbolster** [comment]
It's technically alive so that counts for something discourse.farsetlabs.org.uk
