### ISSUE TITLE
Write up a blog post and policy document explaining/promoting 'somebody-should'

### ISSUE THREAD

**Issue by andrewbolster** [FarsetLabs/somebody-should#3]
Issue tracker is no good if people don't know about it!

**Comment by andrewbolster** [comment]
Pending Post in Blog

**Comment by awflwafl** [comment]
@andrewbolster What happened to our monitor in the co-working space that displayed events and such?

Might be a good place to show something like 'open issues'. We use some sort of program to carousel between tabs with various pieces of information in our office.

**Comment by andrewbolster** [comment]
https://blog.farsetlabs.org.uk/2018/11/somebody-should-a-good-idea-worth-stealing/
