### ISSUE TITLE
Network socket is hanging off the wall

### ISSUE THREAD

**Issue by oibind** [FarsetLabs/somebody-should#9]
**Describe the bug**
one of the network sockets in the co-working space is hanging off the wall

**Expected behavior**
should not be hanging off the wall

**Screenshots/Evidence**
![img_20181030_172019](https://user-images.githubusercontent.com/25280584/47737543-0f3af900-dc69-11e8-8853-272a748a4691.jpg)

**Additional context**
n/a

**Comment by andrewbolster** [comment]
@Stealthii I assume this is just a new box?

**Comment by andrewbolster** [comment]
Fixed during renovations 😂
